spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/jpaDB?createDatabaseIfNotExist=true
    username: root
    password: root


