spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/jpaDB?createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml


